version: '3.9'
services:
  nginx:
    build:
      dockerfile: nginx/Dockerfile
      context: .
    ports:
      - "81:80"
      - "443:443"
    depends_on:
      - web
    networks:
      - travel_network

  db:
    image: postgres:16.3

    environment:
      - POSTGRES_DB=${PG_DB}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    restart: on-failure
    ports:
      - ${PG_PORT}:5432
    volumes:
      - postgresql-travel-volume:/var/lib/postgresql/data
      - ./scripts/postgres:/docker-entrypoint-initdb.d

    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${PG_USER}", "-d", "${PG_DB}"]
      interval: 5s
      retries: 5
    networks:
      - travel_network

  web:
    build:
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    environment:
      BIND_PORT: ${BIND_PORT}
      BIND_HOST: ${BIND_HOST}
    ports:
      - "${BIND_PORT}:${BIND_PORT}"
    restart: on-failure
    volumes:
      - ./:/code
    depends_on:
      db:
        condition: service_healthy
    networks:
      - travel_network

  redis:
    image: redis:6.2.4
    command:
      - "--requirepass ${REDIS_PASSWORD}"
      - "--appendonly yes"
      - "--appendfilename 'appendonly.aof'"
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    environment:
      - REDIS_HOST_PASSWORD=${REDIS_PASSWORD}
    networks:
      - travel_network


  prometheus:
    image: prom/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus_config.yml"
    ports:
      - "9090:9090"
    restart: unless-stopped
    depends_on:
      - web
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus

volumes:
   prom_data:
   postgresql-travel-volume:

networks:
  travel_network:
    external: True